name: PIPELINE1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Intalar as dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Gerar artefato ZIP
        run: zip -r pipeline-demo.zip .

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: codigo-buildado
          path: pipeline-demo.zip

      - name: Teste
        run: pytest
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production

    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: codigo-buildado
      
      - name: Extrair artefato
        run: unzip pipeline-demo.zip

      - name: Simular deploy
        run: echo "Deploy feito com sucesso em produção"

      - [cite_start]name: Análise com SonarCloud [cite: 46]
        [cite_start]uses: SonarSource/sonarcloud-github-action@v2 [cite: 47]
        with:
          args: >
            -Dsonar.projectKey=SEU_PROJECT_KEY [cite: 50]
            -Dsonar.organization=SUA_ORGANIZATION [cite: 51]
        env:
          [cite_start]SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} [cite: 53]