name: PIPELINE1

on:
  push:
    branches:
      - main


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar as dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Análise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=guicoelhoo_pipeline
            -Dsonar.organization=guicoelhoo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Gerar artefato ZIP
        run: zip -r pipeline-demo.zip .

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: codigo-buildado
          path: pipeline-demo.zip

      - name: Teste
        run: pytest
         
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production

    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: codigo-buildado
      
      - name: Extrair artefato
        run: unzip pipeline-demo.zip

      - name: Simular deploy
        run: echo "Deploy feito com sucesso em produção"